# when rebuilding older libcxx, we need pin the libcxx version
# of libcxx-testing, to avoid that the downstream test pulls in
# a newer libcxx than the one being built/tested.
libcxx_major:
  - 19
  # for boostrapping purposes, we also need a build of
  # libcxx-testing without a libcxx constraint
  - 99
# the builds of libcxx-testing depend on a specific
# clang version; to test new libcxx against old clang
# we need to build libcxx-testing for several versions.
c_compiler_version:         # [osx]
  - 19                      # [osx]
  - 18                      # [osx]
  - 17                      # [osx]
  - 16                      # [osx]
cxx_compiler_version:       # [osx]
  - 19                      # [osx]
  - 18                      # [osx]
  - 17                      # [osx]
  - 16                      # [osx]
# not linked to LLVM; can stay constant,
# but must have the same length as above
fortran_compiler_version:   # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
