# the builds of libcxx-testing depend on a specific
# clang version; to test new libcxx against old clang
# we need to build libcxx-testing for several versions.
c_compiler_version:         # [osx]
  - 16                      # [osx]
  - 15                      # [osx]
  - 14                      # [osx]
  - 13                      # [osx]
  - 12                      # [osx]
  - 11                      # [osx]
cxx_compiler_version:       # [osx]
  - 16                      # [osx]
  - 15                      # [osx]
  - 14                      # [osx]
  - 13                      # [osx]
  - 12                      # [osx]
  - 11                      # [osx]
# not linked to LLVM; can stay constant,
# but must have the same length as above
fortran_compiler_version:   # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
  - 13                      # [osx]
